### ISSUE TITLE
Contribution with extended functionality - updates save_vsr_300 file

### ISSUE THREAD

**Issue by cbjornerud** [Ztaeyn/HomeAssistant-VTR-Modbus#18]
### Changes made 2023-12-29
# added sensors for fan speed at all levels
# added control of normal fan speed, supply and exhaust individually
# added unique ID to all entities: switches, inputs, helpers and sensors
# Unique ID enables adding the entities to one or more areas.

[save_vsr_300_textformat.txt](https://github.com/Ztaeyn/HomeAssistant-VTR-Modbus/files/13796249/save_vsr_300_textformat.txt)

**Comment by Ztaeyn** [comment]
Thank you good sir!
I've incorporated these along with a glass of wine :)
