### ISSUE TITLE
supply_temperature address vsr30012102_holding_1 is duplicate, second entry not loaded

### ISSUE THREAD

**Issue by austermkv** [Ztaeyn/HomeAssistant-VTR-Modbus#23]
Thanks for your work! 
Modbus address 12102 is used twice, both for "climates" and for "sensors". This fails in HA 2024.3, and only the climates one is being used by HA, not the vsr300_supply_temperature (Entity not availble).

**Comment by Ztaeyn** [comment]
Hi, thank you for noticing this. I was not aware. I removed the duplicate use, and recreated a template sensor reading the value from the climate controller.
Seems OK now, check the latest changes. If you just copy the file and reboot, you will end up with a secondary sensor_2, then just delete the old sensor in HA and rename the new by removing "_2".

**Comment by austermkv** [comment]
Works like a charm, thanks a lot!
